# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

# CI name
name: OWO

# events which can trigger action 
on:
  push: # when push commit
    branches: [ main ] # specify the main branch
  release: # when push a tag commit
    branches: [ main ]

jobs:
  build: # job build
    runs-on: ubuntu-latest # The type of machine to run the job on
    steps: # a sequence of tasks
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  test: # job test
    runs-on: ubuntu-latest
    needs: [ build ] # dependency of job, i.e. run after build done

    steps:
    - uses: actions/checkout@v2
    - name: generate file
      run: |
      mkdir -p path/to/artifact
      echo hello > path/to/artifact/world.txt
    
    - name: output test report
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: path/to/artifact/world.txt

  # assemble: # job assemble
  #   runs-on: ubuntu-latest
  #   needs: [ test ]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-java@v1
  #   - name: create jar file
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: Package
  #       path: build/libs
