# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

# CI name
name: OWO

# events which can trigger action 
on: push # when push commit
    # branches: [ main ] # specify the main branch

jobs:
  Build: # job build
    runs-on: ubuntu-latest # The type of machine to run the job on
    steps: # a sequence of tasks
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - uses: actions/cache@v2 # build cache
      name: Cache test report
      with:
        path: build/reports/tests/test
        key: test-report
    - uses: actions/cache@v2 # build cache
      name: Cache jar file
      with:
        path: build/libs/st_nycu_lab4-1.0-SNAPSHOT.jar
        key: build-jar

  Test: # job test
    runs-on: ubuntu-latest
    needs: [ build ] # dependency of job, i.e. run after build done
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      name: Get test report cache
      with:
        path: build/reports/tests/test
        key: test-report
    - uses: actions/upload-artifact@v2
      name: Upload test report
      with:
        name: testReport
        path: build/reports/tests/test

  Assemble: # job assemble
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      name: Get jar cache
      with:
        path: build/libs/st_nycu_lab4-1.0-SNAPSHOT.jar
        key: build-jar
    - name: Upload jar file
      uses: actions/upload-artifact@v2
      with:
        name: buildJar
        path: build/libs/st_nycu_lab4-1.0-SNAPSHOT.jar

  Release:
    runs-on: ubuntu-latest
    needs: [ assemble ]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      name: Get jar file  
      with:
        path: build/libs/st_nycu_lab4-1.0-SNAPSHOT.jar
        key: buildJar
    - name: release jar file
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/libs/st_nycu_lab4-1.0-SNAPSHOT.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
